--- # My First Playbook
- hosts: webhosts
  user: test
  connection: ssh
  sudo: yes
  gather_facts: no
  
  vars:
    playbook_version: 1
  vars_files:
    - conf/copyright.yml 
    - conf/webdefaults.yml  

  tasks:
    - name: Install Apache Web Server
      yum: pkg=httpd state=installed
