--- # Notify
- hosts: debianhost
  user: test
  connection: ssh
  sudo: yes
  gather_facts: no

  tasks:
    - name: Installs the Apache Web Server
      apt: pkg=apache2 state=present
      notify: start_apache

  handlers:
    - name: start_apache
      service: name=apache2 state=restarted
